### ISSUE TITLE
推荐这个 cuda 入门教程

### ISSUE THREAD

**Issue by MelodicDrumstep** [l0ngc/hpc-learning#4]
视频： https://www.youtube.com/watch?v=A1EkI5t_CJI&list=PL6RdenZrxrw-zNX7uuGppWETdxt_JxdMj&index=2

作业框架：https://github.com/olcf/cuda-training-series

然后再结合官方文档 https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#programming-model

高效率极速入门 cuda

**Comment by l0ngc** [comment]
nice！感谢！已添加！
